### ISSUE TITLE
java.lang.IllegalArgumentException: Media is read-only

### ISSUE THREAD

**Issue by HTC600** [seokyeol/ExifCopy#1] opened 2024-03-04 20:42 UTC
Android 9
Please fix it

java.lang.IllegalArgumentException: Media is read-only
	at android.database.DatabaseUtils.readExceptionFromParcel(Unknown Source:57)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(Unknown Source:14)
	at android.content.ContentProviderProxy.openAssetFile(Unknown Source:42)
	at android.content.ContentResolver.openAssetFileDescriptor(Unknown Source:191)
	at android.content.ContentResolver.openFileDescriptor(Unknown Source:0)
	at android.content.ContentResolver.openFileDescriptor(Unknown Source:1)
	at d3.c.onClick(SourceFile:6)
	at android.view.View.performClick(Unknown Source:53)
	at [com.google.android](http://com.google.android/).material.button.MaterialButton.performClick(Unknown Source:3)
	at android.view.View.performClickInternal(Unknown Source:3)
	at android.view.View.access$3100(Unknown Source:0)
	at android.view.View$[PerformClick.run](http://performclick.run/)(Unknown Source:2)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:207)
	at [android.app](http://android.app/).ActivityThread.main(Unknown Source:116)
	at java.lang.reflect.Method.invoke(Native Method)
	at [com.android](http://com.android/).internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)(Unknown Source:11)
	at [com.android](http://com.android/).internal.os.ZygoteInit.main(Unknown Source:284)

**Comment by seokyeol** [comment] 2024-06-18 13:05
Sorry for the late response.
The issue you mentioned seems to be caused by the Storage Access Framework in older Android versions returning a read-only URI when we try to access a file through certain media tabs.
Until the issue is resolved, please select files through actual storage paths (e.g., `SDCARD`, `Downloads`) instead of the media tabs (e.g., `Recent`, `Images`) in the SAF.

<img src="https://github.com/seokyeol/ExifCopy/assets/89076501/7f4f4f28-9ba0-4b82-b110-d475daf65493" width="300"/>

**Comment by seokyeol** [comment] 2024-06-18 15:24
I have just committed the fix :)

**Closed as completed by seokyeol** 2024-06-18 15:24 UTC

**Comment by HTC600** [comment] 2024-06-18 15:28
Thanks a lot.
--
Отправлено из Mail.ru для Android вторник, 18 июня 2024г., 18:25 +03:00 от Seokyeol Kim  ***@***.*** :
